ARG BUILD_FROM

FROM $BUILD_FROM
#FROM golang:1.14 AS go

ENV LANG C.UTF-8

#LABEL "TestLabel"="Here"
EXPOSE 7080

WORKDIR /HassiGo
COPY bin .
RUN chmod a+x ./hassigo

#COPY --from=go /usr/local/go/ /usr/local/go/

#RUN export PATH="/usr/local/go/bin:$PATH" && go version

ARG GOLANG_VERSION=1.14.3

#we need the go version installed from apk to bootstrap the custom version built from source
RUN apk update && apk add go gcc bash musl-dev openssl-dev ca-certificates && update-ca-certificates

RUN wget https://dl.google.com/go/go$GOLANG_VERSION.src.tar.gz && tar -C /usr/local -xzf go$GOLANG_VERSION.src.tar.gz

RUN cd /usr/local/go/src && ./make.bash

ENV PATH=$PATH:/usr/local/go/bin

RUN rm go$GOLANG_VERSION.src.tar.gz

#we delete the apk installed version to avoid conflict
RUN apk del go

RUN go version


LABEL \
    io.hass.name="HassiGo" \
    io.hass.description="desc" \
    io.hass.type="addon" \
    io.hass.version=${BUILD_VERSION}

CMD [ "./hassigo" ]
