ARG BUILD_FROM
FROM $BUILD_FROM

ENV LANG C.UTF-8

#LABEL "TestLabel"="Here"
EXPOSE 7080


RUN apk add --no-cache \
		ca-certificates

COPY --from=golang:1.15.6-alpine /usr/local/go/ /usr/local/go/
 
ENV PATH="/usr/local/go/bin:${PATH}"

RUN go version


ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH




WORKDIR /HassiGo
COPY bin .
RUN chmod a+x ./hassigo

LABEL \
    io.hass.name="HassiGo" \
    io.hass.description="HassiGo description" \
    io.hass.arch="${BUILD_ARCH}" \
    io.hass.type="addon" \
    io.hass.version=${BUILD_VERSION} \
    maintainer="Kyle Gibbons <kyle@kylegibbons.com>" \
    org.opencontainers.image.title="HassiGo" \
    org.opencontainers.image.description="HassiGo description" \
    org.opencontainers.image.vendor="Kyle Gibbons" \
    org.opencontainers.image.authors="Kyle Gibbons <kyle@kylegibbons.com>" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.url="https://kylegibbons.com" \
    org.opencontainers.image.source="https://github.com/kylegibbons/hassigo" \
    org.opencontainers.image.documentation="https://github.com/kylegibbons/hassigo" \
    org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.revision=${BUILD_REF} \
    org.opencontainers.image.version=${BUILD_VERSION}

CMD [ "./hassigo" ]
